event_nats/nats_jetstream: drop 3 unused locals in mi_nats_stream_create
gcc-10 with -Werror reports:

  nats_jetstream.c:421:9:  error: unused variable 'max_msgs_d'   [-Werror=unused-variable]
  nats_jetstream.c:421:25: error: unused variable 'max_bytes_d'  [-Werror=unused-variable]
  nats_jetstream.c:421:42: error: unused variable 'max_age_d'    [-Werror=unused-variable]

The three doubles were declared and zeroed but never referenced
again in mi_nats_stream_create -- presumably staged for an MI param
parser that ended up using a different code path.  Drop the line.